In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
df=pd.read_csv('ai_policy_and_ethics.csv')
df

,respondent_id,company_has_ai_policy,ai_bias_concern_level,data_privacy_concern_level,supports_ai_regulation,has_experienced_ai_misuse,trust_in_ai_decisions
0,R00001,No,5,5,Neutral,No,Low
1,R00002,Don't know,3,1,Agree,No,High
2,R00003,Yes - formal,5,5,Strongly agree,Unsure,Moderate
3,R00004,No,3,4,Agree,No,Low
4,R00005,Yes - informal,3,3,Agree,Unsure,High
...,...,...,...,...,...,...,...
11995,R11996,Don't know,5,2,Agree,No,Moderate
11996,R11997,No,4,4,Agree,Unsure,Low
11997,R11998,Yes - formal,3,5,Strongly disagree,No,Moderate
11998,R11999,No,3,1,Agree,No,Low
11999,R12000,Yes - formal,3,1,Agree,Unsure,High

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   respondent_id               12000 non-null  str
 1   company_has_ai_policy       12000 non-null  str
 2   ai_bias_concern_level       12000 non-null  int64
 3   data_privacy_concern_level  12000 non-null  int64
 4   supports_ai_regulation      12000 non-null  str
 5   has_experienced_ai_misuse   12000 non-null  str
 6   trust_in_ai_decisions       12000 non-null  str
dtypes: int64(2), str(5)
memory usage: 1.0 MB

In [4]:
df.shape

(12000, 7)

In [5]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()
df

,respondent_id,company_has_ai_policy,ai_bias_concern_level,data_privacy_concern_level,supports_ai_regulation,has_experienced_ai_misuse,trust_in_ai_decisions
0,R00001,No,5,5,Neutral,No,Low
1,R00002,Don't know,3,1,Agree,No,High
2,R00003,Yes - formal,5,5,Strongly agree,Unsure,Moderate
3,R00004,No,3,4,Agree,No,Low
4,R00005,Yes - informal,3,3,Agree,Unsure,High
...,...,...,...,...,...,...,...
11995,R11996,Don't know,5,2,Agree,No,Moderate
11996,R11997,No,4,4,Agree,Unsure,Low
11997,R11998,Yes - formal,3,5,Strongly disagree,No,Moderate
11998,R11999,No,3,1,Agree,No,Low
11999,R12000,Yes - formal,3,1,Agree,Unsure,High

In [7]:
df.isnull().sum()

respondent_id                 0
company_has_ai_policy         0
ai_bias_concern_level         0
data_privacy_concern_level    0
supports_ai_regulation        0
has_experienced_ai_misuse     0
trust_in_ai_decisions         0
dtype: int64

In [ ]:
df["company_has_ai_policy"]= df["data_privacy_concern_level"].fillna(df["ai_bias_concern_level"].median())
df

,respondent_id,company_has_ai_policy,ai_bias_concern_level,data_privacy_concern_level,supports_ai_regulation,has_experienced_ai_misuse,trust_in_ai_decisions
0,R00001,5,5,5,Neutral,No,Low
1,R00002,1,3,1,Agree,No,High
2,R00003,5,5,5,Strongly agree,Unsure,Moderate
3,R00004,4,3,4,Agree,No,Low
4,R00005,3,3,3,Agree,Unsure,High
...,...,...,...,...,...,...,...
11995,R11996,2,5,2,Agree,No,Moderate
11996,R11997,4,4,4,Agree,Unsure,Low
11997,R11998,5,3,5,Strongly disagree,No,Moderate
11998,R11999,1,3,1,Agree,No,Low
11999,R12000,1,3,1,Agree,Unsure,High

In [9]:
df.columns

Index(['respondent_id', 'company_has_ai_policy', 'ai_bias_concern_level',
       'data_privacy_concern_level', 'supports_ai_regulation',
       'has_experienced_ai_misuse', 'trust_in_ai_decisions'],
      dtype='str')

In [11]:
#AI POLICY DISTRIBUTION-BAR GRAPH
import plotly.express as px

fig = px.bar(
    df['company_has_ai_policy'].value_counts(),
    title='Companies with AI Policy'
)
fig.show()

In [12]:
# AI Bias Concern Level — Pie Chart
fig = px.pie(
    df,
    names='ai_bias_concern_level',
    title='AI Bias Concern Level'
)

fig.show()

In [ ]:
# Data Privacy Concern — Bar Chart
privacy = df['data_privacy_concern_level'].value_counts().reset_index()

fig = px.bar(
    privacy,
    x='data_privacy_concern_level',
    y='count',
    title='Data Privacy Concern Level',
    labels={
        'data_privacy_concern_level': 'Privacy Concern',
        'count': 'Number of Respondents'
    }
)

fig.show()

In [14]:
# Support for AI Regulation — Pie Chart
fig = px.pie(
    df,
    names='supports_ai_regulation',
    title='Support for AI Regulation'
)

fig.show()

In [21]:
# Trust in AI Decisions — Bar Chart
trust = df['trust_in_ai_decisions'].value_counts().reset_index()

fig = px.bar(
    trust,
    x='trust_in_ai_decisions',
    y='count',
    title='Trust in AI Decisions',
    labels={
        'trust_in_ai_decisions': 'Trust Level',
        'count': 'Number of Respondents'
    }
)

fig.show()