In [2]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Lenovo\miniconda3\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Lenovo\miniconda3\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Lenovo\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Lenovo\miniconda3\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\Lenovo\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd
import seaborn as  sns
import matplotlib.pyplot as plt
import plotly.express as px

In [4]:
df= pd.read_csv('salary_and_satisfaction.csv')
df

,respondent_id,annual_salary_usd,salary_change_yoy_pct,job_satisfaction_score,career_growth_outlook,ai_job_replacement_fear,job_search_status,received_ai_related_promotion,work_life_balance_score,burnout_level
0,R00001,63700.0,9.0,4,Neutral,Unlikely,Open to offers,No,1,Mild
1,R00002,124600.0,15.1,1,Positive,Somewhat likely,Recently changed,Yes,5,Mild
2,R00003,39800.0,5.2,3,Negative,Very likely,Not looking,No,4,Severe
3,R00004,65400.0,2.2,4,Very positive,Unlikely,Recently changed,No,3,Moderate
4,R00005,53800.0,20.4,2,Positive,Very likely,Actively looking,Yes,4,Severe
...,...,...,...,...,...,...,...,...,...,...
11995,R11996,101900.0,9.0,4,Negative,Neutral,Open to offers,No,5,Mild
11996,R11997,32000.0,-0.5,4,Very positive,Very unlikely,Recently changed,No,2,NaN
11997,R11998,42700.0,14.3,3,Neutral,Very unlikely,Open to offers,Yes,4,Mild
11998,R11999,236100.0,-5.1,2,Neutral,Unlikely,Open to offers,No,3,NaN
11999,R12000,104900.0,2.5,3,Neutral,Neutral,Open to offers,No,4,NaN

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   respondent_id                  12000 non-null  str
 1   annual_salary_usd              12000 non-null  float64
 2   salary_change_yoy_pct          12000 non-null  float64
 3   job_satisfaction_score         12000 non-null  int64
 4   career_growth_outlook          12000 non-null  str
 5   ai_job_replacement_fear        12000 non-null  str
 6   job_search_status              12000 non-null  str
 7   received_ai_related_promotion  12000 non-null  str
 8   work_life_balance_score        12000 non-null  int64
 9   burnout_level                  9586 non-null   str
dtypes: float64(2), int64(2), str(6)
memory usage: 937.6 KB

In [6]:
df.shape

(12000, 10)

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df= df.drop_duplicates()
df

,respondent_id,annual_salary_usd,salary_change_yoy_pct,job_satisfaction_score,career_growth_outlook,ai_job_replacement_fear,job_search_status,received_ai_related_promotion,work_life_balance_score,burnout_level
0,R00001,63700.0,9.0,4,Neutral,Unlikely,Open to offers,No,1,Mild
1,R00002,124600.0,15.1,1,Positive,Somewhat likely,Recently changed,Yes,5,Mild
2,R00003,39800.0,5.2,3,Negative,Very likely,Not looking,No,4,Severe
3,R00004,65400.0,2.2,4,Very positive,Unlikely,Recently changed,No,3,Moderate
4,R00005,53800.0,20.4,2,Positive,Very likely,Actively looking,Yes,4,Severe
...,...,...,...,...,...,...,...,...,...,...
11995,R11996,101900.0,9.0,4,Negative,Neutral,Open to offers,No,5,Mild
11996,R11997,32000.0,-0.5,4,Very positive,Very unlikely,Recently changed,No,2,NaN
11997,R11998,42700.0,14.3,3,Neutral,Very unlikely,Open to offers,Yes,4,Mild
11998,R11999,236100.0,-5.1,2,Neutral,Unlikely,Open to offers,No,3,NaN
11999,R12000,104900.0,2.5,3,Neutral,Neutral,Open to offers,No,4,NaN

In [9]:
df.isnull().sum()

respondent_id                       0
annual_salary_usd                   0
salary_change_yoy_pct               0
job_satisfaction_score              0
career_growth_outlook               0
ai_job_replacement_fear             0
job_search_status                   0
received_ai_related_promotion       0
work_life_balance_score             0
burnout_level                    2414
dtype: int64

In [10]:
df.columns

Index(['respondent_id', 'annual_salary_usd', 'salary_change_yoy_pct',
       'job_satisfaction_score', 'career_growth_outlook',
       'ai_job_replacement_fear', 'job_search_status',
       'received_ai_related_promotion', 'work_life_balance_score',
       'burnout_level'],
      dtype='str')

In [11]:
df["annual_salary_usd"]= df["salary_change_yoy_pct"].fillna(df["career_growth_outlook"].mode())
df

,respondent_id,annual_salary_usd,salary_change_yoy_pct,job_satisfaction_score,career_growth_outlook,ai_job_replacement_fear,job_search_status,received_ai_related_promotion,work_life_balance_score,burnout_level
0,R00001,9.0,9.0,4,Neutral,Unlikely,Open to offers,No,1,Mild
1,R00002,15.1,15.1,1,Positive,Somewhat likely,Recently changed,Yes,5,Mild
2,R00003,5.2,5.2,3,Negative,Very likely,Not looking,No,4,Severe
3,R00004,2.2,2.2,4,Very positive,Unlikely,Recently changed,No,3,Moderate
4,R00005,20.4,20.4,2,Positive,Very likely,Actively looking,Yes,4,Severe
...,...,...,...,...,...,...,...,...,...,...
11995,R11996,9.0,9.0,4,Negative,Neutral,Open to offers,No,5,Mild
11996,R11997,-0.5,-0.5,4,Very positive,Very unlikely,Recently changed,No,2,NaN
11997,R11998,14.3,14.3,3,Neutral,Very unlikely,Open to offers,Yes,4,Mild
11998,R11999,-5.1,-5.1,2,Neutral,Unlikely,Open to offers,No,3,NaN
11999,R12000,2.5,2.5,3,Neutral,Neutral,Open to offers,No,4,NaN

In [ ]:
#Annual Salary Distribution — Histogram
import plotly.express as px
import pandas as pd

df['annual_salary_usd'] = pd.to_numeric(
    df['annual_salary_usd'],
    errors='coerce'
)

fig = px.histogram(
    df,
    x='annual_salary_usd',
    title='Annual Salary Distribution'
)

fig.show()

In [15]:
# Job Satisfaction Score — Bar Chart
satisfaction = df['job_satisfaction_score'].value_counts().sort_index().reset_index()

fig = px.bar(
    satisfaction,
    x='job_satisfaction_score',
    y='count',
    title='Job Satisfaction Score'
)

fig.show()

In [16]:
# AI Job Replacement Fear — Pie Chart
fig = px.pie(
    df,
    names='ai_job_replacement_fear',
    title='Fear of AI Job Replacement'
)

fig.show()

In [17]:
#Burnout Level — Bar Chart
burnout = df['burnout_level'].value_counts().reset_index()

fig = px.bar(
    burnout,
    x='burnout_level',
    y='count',
    title='Employee Burnout Level'
)

fig.show()

In [18]:
# Work-Life Balance Score — Bar Chart
balance = df['work_life_balance_score'].value_counts().sort_index().reset_index()

fig = px.bar(
    balance,
    x='work_life_balance_score',
    y='count',
    title='Work-Life Balance Score'
)

fig.show()