In [1]:
import pandas as pd
import seaborn as  sns
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
df= pd.read_csv('skills_and_training.csv')
df

,respondent_id,skills,num_skills,top_certification,weekly_learning_hours,primary_learning_platform,learned_genai_skills_2024_2026,employer_provides_ai_training
0,R00001,Computer Vision; Feature Engineering; Python; ...,9,NaN,3,Fast.ai,Yes,Partially
1,R00002,SQL; Graph Neural Networks; Generative AI; Fea...,10,NaN,8,Self-study (books/papers),Yes,No
2,R00003,Python; Prompt Engineering; PyTorch; Spark; R;...,8,AWS ML Specialty,8,Kaggle Learn,Yes,No
3,R00004,Azure; Time Series Analysis; R; Scikit-learn; ...,6,AWS ML Specialty,12,University courses,Yes,Yes
4,R00005,Time Series Analysis; R; PyTorch; Fine-tuning ...,9,TensorFlow Developer Certificate,15,University courses,No,No
...,...,...,...,...,...,...,...,...
11995,R11996,Generative AI; Feature Engineering; Docker; Ed...,5,Google Professional ML Engineer,8,edX,Yes,Yes
11996,R11997,Prompt Engineering; Azure; Docker; Computer Vi...,5,Coursera ML Certificate,0,YouTube,Yes,No
11997,R11998,Graph Neural Networks; Fine-tuning LLMs; LangC...,5,NaN,11,Udemy,No,Partially
11998,R11999,NLP; Time Series Analysis; Data Visualization;...,8,TensorFlow Developer Certificate,7,Fast.ai,No,Yes
11999,R12000,Fine-tuning LLMs; Data Visualization; Graph Ne...,6,TensorFlow Developer Certificate,3,Company training,No,Partially

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   respondent_id                   12000 non-null  str
 1   skills                          12000 non-null  str
 2   num_skills                      12000 non-null  int64
 3   top_certification               8370 non-null   str
 4   weekly_learning_hours           12000 non-null  int64
 5   primary_learning_platform       12000 non-null  str
 6   learned_genai_skills_2024_2026  12000 non-null  str
 7   employer_provides_ai_training   12000 non-null  str
dtypes: int64(2), str(6)
memory usage: 2.4 MB

In [4]:
df.shape

(12000, 8)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df= df.drop_duplicates()
df

,respondent_id,skills,num_skills,top_certification,weekly_learning_hours,primary_learning_platform,learned_genai_skills_2024_2026,employer_provides_ai_training
0,R00001,Computer Vision; Feature Engineering; Python; ...,9,NaN,3,Fast.ai,Yes,Partially
1,R00002,SQL; Graph Neural Networks; Generative AI; Fea...,10,NaN,8,Self-study (books/papers),Yes,No
2,R00003,Python; Prompt Engineering; PyTorch; Spark; R;...,8,AWS ML Specialty,8,Kaggle Learn,Yes,No
3,R00004,Azure; Time Series Analysis; R; Scikit-learn; ...,6,AWS ML Specialty,12,University courses,Yes,Yes
4,R00005,Time Series Analysis; R; PyTorch; Fine-tuning ...,9,TensorFlow Developer Certificate,15,University courses,No,No
...,...,...,...,...,...,...,...,...
11995,R11996,Generative AI; Feature Engineering; Docker; Ed...,5,Google Professional ML Engineer,8,edX,Yes,Yes
11996,R11997,Prompt Engineering; Azure; Docker; Computer Vi...,5,Coursera ML Certificate,0,YouTube,Yes,No
11997,R11998,Graph Neural Networks; Fine-tuning LLMs; LangC...,5,NaN,11,Udemy,No,Partially
11998,R11999,NLP; Time Series Analysis; Data Visualization;...,8,TensorFlow Developer Certificate,7,Fast.ai,No,Yes
11999,R12000,Fine-tuning LLMs; Data Visualization; Graph Ne...,6,TensorFlow Developer Certificate,3,Company training,No,Partially

In [7]:
df.isnull().sum()

respondent_id                        0
skills                               0
num_skills                           0
top_certification                 3630
weekly_learning_hours                0
primary_learning_platform            0
learned_genai_skills_2024_2026       0
employer_provides_ai_training        0
dtype: int64

In [8]:
df.columns

Index(['respondent_id', 'skills', 'num_skills', 'top_certification',
       'weekly_learning_hours', 'primary_learning_platform',
       'learned_genai_skills_2024_2026', 'employer_provides_ai_training'],
      dtype='str')

In [9]:
df['skills']= df['num_skills'].fillna(df['weekly_learning_hours'].mode())
df

,respondent_id,skills,num_skills,top_certification,weekly_learning_hours,primary_learning_platform,learned_genai_skills_2024_2026,employer_provides_ai_training
0,R00001,9,9,NaN,3,Fast.ai,Yes,Partially
1,R00002,10,10,NaN,8,Self-study (books/papers),Yes,No
2,R00003,8,8,AWS ML Specialty,8,Kaggle Learn,Yes,No
3,R00004,6,6,AWS ML Specialty,12,University courses,Yes,Yes
4,R00005,9,9,TensorFlow Developer Certificate,15,University courses,No,No
...,...,...,...,...,...,...,...,...
11995,R11996,5,5,Google Professional ML Engineer,8,edX,Yes,Yes
11996,R11997,5,5,Coursera ML Certificate,0,YouTube,Yes,No
11997,R11998,5,5,NaN,11,Udemy,No,Partially
11998,R11999,8,8,TensorFlow Developer Certificate,7,Fast.ai,No,Yes
11999,R12000,6,6,TensorFlow Developer Certificate,3,Company training,No,Partially

In [10]:
# Top Skills — Bar Chart
import plotly.express as px

skills = df['skills'].value_counts().head(10).reset_index()

fig = px.bar(
    skills,
    x='skills',
    y='count',
    title='Top 10 Skills'
)

fig.show()

In [11]:
# Primary Learning Platform — Bar Chart
platform = df['primary_learning_platform'].value_counts().reset_index()

fig = px.bar(
    platform,
    x='primary_learning_platform',
    y='count',
    title='Primary Learning Platforms'
)

fig.show()

In [12]:
# Weekly Learning Hours — Histogram
df['weekly_learning_hours'] = pd.to_numeric(
    df['weekly_learning_hours'],
    errors='coerce'
)

fig = px.histogram(
    df,
    x='weekly_learning_hours',
    title='Weekly Learning Hours'
)

fig.show()

In [13]:
# GenAI Skills Learned — Pie Chart
fig = px.pie(
    df,
    names='learned_genai_skills_2024_2026',
    title='Learned GenAI Skills (2024–2026)'
)

fig.show()

In [14]:
# Employer AI Training — Pie Chart
fig = px.pie(
    df,
    names='employer_provides_ai_training',
    title='Employer-Provided AI Training'
)

fig.show()